### ISSUE TITLE
Why have `Error.prototype.cause` be the empty string?

### ISSUE THREAD

**Issue by bakkot** [tc39/proposal-error-cause#13]
It's weird to me that `(new Error).cause` would be `""` rather than `undefined`.

**Comment by ljharb** [comment]
`(new Error).message` is the empty string.

**Comment by bakkot** [comment]
Yes, and that's a bit weird too, but at least the empty string is a sensible value for a message. Since the intent of this field is to hold another `Error` value, the empty string is not a sensible value for it.

**Comment by ljharb** [comment]
Ah, it wasn't clear to me that that was the intention. If indeed that's the case, then I would absolutely expect the prototype value to be `undefined`.

**Comment by hax** [comment]
As the slide, using the empty string may help the code like `String(error.cause)` to not print `"undefined"`.

**Comment by legendecas** [comment]
We had a discussion on this https://github.com/tc39/proposal-error-cause/pull/9#discussion_r501174474. The idea is to prevent printing `"undefined"` in common cases.

**Comment by bakkot** [comment]
That's not a thing the language usually cares about. My preference is that there should be no `cause` property on the prototype of any kind, but if there must be such a property it should definitely be `undefined`, not the empty string.

**Comment by littledan** [comment]
I'm sympathetic with the goal of making sure `"undefined"` doesn't pop up in even more places, but isn't this what `??` is for? So you can do `error.cause ?? ""` when you need it.

For this reason, I weakly share @bakkot 's preference here.

**Comment by kriskowal** [comment]
I favor the `undefined` default. (The informal intuition of the type should be `Error?`, not `'' | Error`).

**Comment by legendecas** [comment]
I'm personally preferring the `undefined` default value. As the choice was made previously, it will be great to hear from @ljharb and @hemanth.

**Comment by ljharb** [comment]
I'm content with `undefined`, especially if `toString` ends up explicitly describing that `cause` shouldn't be stringified when nullish.

**Comment by littledan** [comment]
I guess the current spec text omits the cause from the `toString`. Is this intentional?

**Comment by hemanth** [comment]
I vote for `undefined` too.

**Comment by legendecas** [comment]
> @ljharb: I'm content with undefined, especially if toString ends up explicitly describing that cause shouldn't be stringified when nullish.
> @littledan: I guess the current spec text omits the cause from the `toString`. Is this intentional?

We can discuss `toString` in #16.

**Comment by ExE-Boss** [comment]
Why not use `null` as the missing value default?

**Comment by bakkot** [comment]
Why would you?

**Comment by domenic** [comment]
+1 to no prototype property. That also matches the decision make for `AggregateError.prototype` not having a `errors` property.
