### ISSUE TITLE
Reviewers

### ISSUE THREAD

**Issue by codehag** [tc39/proposal-error-cause#15]
Hi, and congratulations on stage 2!

Because we were rushed, it looks like we missed reviewers for this. I can probably volunteer. Do you have other reviewers?

**Comment by legendecas** [comment]
Thank you! It will be great to have you reviewing the spec.

I believe there isn't anyone who explicitly stands for reviewers. I'd like to appreciate @ljharb for his reviews on the PRs, and I'd appreciate it if he is still interested in reviewing too.

**Comment by ljharb** [comment]
Happy to be a reviewer! We’ll need to confirm reviewers in the next plenary, of course.

**Comment by codehag** [comment]
I've reviewed it for stage 3, it looks pretty good.

One thing I am not really sure about is the addition of the new abstract operations CreateNonEnumerableDataProperty and InstallErrorCause. They save a total of 4-5 lines, but they add extra checks. I think the goal here was to reduce repetition and make reading easier, but I found the previous version pretty straight forward and maybe a little easier to read than the refactoring. This is a matter of taste. Soft preference for just doing it inline.

**Comment by ljharb** [comment]
I'd asked for the separate AOs since the repetition happened three times and seemed prone to being written and implemented inconsistently. What extra checks are you referring to?

**Comment by legendecas** [comment]
IMO, `CreateNonEnumerableDataPropertyOrThrow` is intuitive to understand in the context with the precedent `CreateDataPropertyOrThrow`. For `InstallErrorCause`, it contains repetive non-common checks (not checking if the `options.cause` is `undefined` but if the `options.cause` is present). It seems to me an AO will help to reduce the chance to be mistaken.

**Comment by codehag** [comment]
As mentioned, it is more a matter of taste. I am fine with it as is (which is why I didn't open an issue).

**Comment by legendecas** [comment]
Thanks for the review! Closing as there is no open question. Feel free to re-open if needed.
